--1. Crear las tablas normalizada de acuerdo con el Modelo planteado.

create table CLIENTES (
                COD_CLIENTE VARCHAR2(8),
                CONSTRAINT PK_CLIENTE PRIMARY key (COD_CLIENTE),
                NOMBRE varchar2(30),
                DISTRITO VARCHAR2(30),
                TELEFONO VARCHAR2(10)
                );
                
                
create table FACTURAS(
                COD_FACTURA CHAR(5),
                CONSTRAINT PK_FACTURAS primary key(COD_FACTURA),
                COD_CLIENTE VARCHAR2(8),
                FECHA_EMISION date,
                IMPORTE_TOTAL number(9,2)
                );
                
alter table FACTURAS ADD CONSTRAINT
                    fk_COD_CLIENTE FOREIGN KEY (COD_CLIENTE)
                    REFERENCES CLIENTES(COD_CLIENTE);
                    
CREATE TABLE PRODUCTOS (
            COD_PRODUCTO CHAR(5),
            CONSTRAINT PK_PRODUCTOS PRIMARY KEY(COD_PRODUCTO),
            DESCRIPCION VARCHAR2(30),
            PRECIO_UNITARIO NUMBER(9,2)
            );
            
CREATE TABLE DETALLE_FACTURAS(
                COD_FACTURA CHAR (5),
                COD_PRODUCTO CHAR(5),
                CANTIDAD NUMBER(5),
                SUBTOTAL NUMBER (9,2)
                );
ALTER TABLE DETALLE_FACTURAS ADD CONSTRAINT
            pf_COD_FACTURA FOREIGN KEY (COD_FACTURA)
            REFERENCES FACTURAS (COD_FACTURA);
            
ALTER TABLE DETALLE_FACTURAS ADD CONSTRAINT
       
            pf_COD_PRODUCTO FOREIGN KEY (COD_PRODUCTO)
            REFERENCES PRODUCTOS (COD_PRODUCTO);


--5. Agregarle a la tabla de Clientes el campo dirección, el cual deberá tener una longitud de 100 caracteres.

ALTER TABLE CLIENTES 
ADD DIRECCION VARCHAR2(100);

--6. Modificar la tabla ‘BASURA’ haciendo que la clave primaria sea siempre una identidad.
--Comenzando ésta en 10.

-- CREANDO TABLA BASURA
DROP TABLE BASURA;
CREATE TABLE BASURA (
     codigo NUMBER(5) GENERATED BY DEFAULT AS IDENTITY(START WITH 10 INCREMENT BY 1),
     descripcion VARCHAR2(30) NOT NULL,
     precio_venta NUMBER(8,2),
     CONSTRAINT PK_BASURA PRIMARY KEY(codigo)
     
);

--7. Insertar en la tabla ‘BASURA’ un registro cuya descripción sea 'LAVARROPAS’ y precio 4500.

INSERT INTO BASURA(descripcion,precio_venta) VALUES('LAVARROPAS','4500');
COMMIT;
--8. Eliminar todos los registros de la tabla ‘BASURA’ que se ha creado con el Script del trabajo práctico.


DELETE FROM BASURA;COMMIT;


--9. Volver a insertar los registros eliminados de la tabla ‘BASURA’ y esta vez eliminar sólo aquellos registros cuyo precio sea superior a 125.

-- INSERTANDO REGISTROS A LA TABLA BASURA
INSERT INTO basura (descripcion,precio_venta) VALUES ('JABONERA',123.12);
INSERT INTO basura (descripcion,precio_venta) VALUES ('PAPELERA',45.56);
INSERT INTO basura (descripcion,precio_venta) VALUES ('MESA LIVING',56.00);
INSERT INTO basura (descripcion,precio_venta) VALUES ('CAFETERA',70.20);
INSERT INTO basura (descripcion,precio_venta) VALUES ('LAMPARA DE PIE',4560);
INSERT INTO basura (descripcion,precio_venta) VALUES ('LICUADORA',1520);
COMMIT;

DELETE FROM BASURA
    WHERE basura.precio_venta > 125;
COMMIT;

--10. Eliminar la Tabla ‘BASURA’.

drop table BASURA;
