CREATE OR REPLACE PACKAGE PKG_VETERINARIA AS
FUNCTION gestion_consultas(p_veterinario VARCHAR2,p_mascota_id NUMBER) RETURN NUMBER;
PROCEDURE GESTION_STOCK_PRODUCTOS(p_producto_id NUMBER, p_cantidad NUMBER);

END PKG_VETERINARIA;
/



CREATE OR REPLACE PACKAGE BODY PKG_VETERINARIA AS
FUNCTION gestion_consultas(p_veterinario VARCHAR2,p_mascota_id NUMBER) RETURN NUMBER;





PROCEDURE GESTION_STOCK_PRODUCTOS(p_producto_id NUMBER, p_cantidad NUMBER);








END PKG_VETERINARIA;
/