CREATE TABLE CONTROL_VETERINARIA (
    ID_AUDITORIA NUMBER(10)   GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TABLA_AFECTADA VARCHAR2(50) NOT NULL,
    OPERACION VARCHAR2(10) NOT NULL CHECK (OPERACION IN ('INSERT','UPDATE','DELETE')),
    ID_REGISTRO NUMBER(10),
    VALOR_ANTERIOR VARCHAR2(500),
    VALOR_NUEVO VARCHAR2(500),
    USUARIO_DB VARCHAR2(60) DEFAULT USER,
    FECHA_EVENTO DATE DEFAULT SYSDATE
);