--1)Desarrollar todas las consignas pedidas y con cada una de las sentencias que responden a ellas armar un archivo que lleve el siguiente formato
-- BII_Apellido_Legajo.sql, por ejemplo BII_TN_GARCIA_12345.sql

--En el Sanatorio "Urgencias Locas" se ha creado una Base de Datos con las tablas que encontrará en el script adjunto. 
-- Sólo se han creado tablas pero no los objetos necesarios para cumplir con ciertas reglas de negocio. Usted como administrador 
--de la Base de Datos deberá desarrollar los disparadores, procedimientos, funciones y paquetes necesarios que permitirán cumplir 
--con aquellas tareas del negocio solicitadas por administrativos, médicos, enfermeros u otros profesionales del sanatorio.

--Nota: todas las consignas deben llevar los bloques anónimos de prueba.


--1)Crear una función que permita obtener la cantidad de diagnósticos distintos de un paciente dando su apellido y DNI.
---Nota: Considerar que podría haber dos pacientes con el mismo apellido y el mismo DNI en cuyo caso devolver -10
/*
CREATE OR REPLACE FUNCTION obtener_cant_diagnosticos(
    p_apellido IN pacientes.apellido%TYPE,
    p_dni      IN pacientes.dni%TYPE
) RETURN NUMBER IS
    l_cant_pacientes    NUMBER;
    l_cant_diagnosticos NUMBER;
BEGIN
     SELECT COUNT(*)
      INTO l_cant_pacientes
      FROM pacientes
     WHERE apellido = p_apellido
       AND dni      = p_dni;

    IF l_cant_pacientes > 1 THEN
        RETURN -10;
        elsif l_cant_pacientes = 0 then

         RETURN  0;
    END IF;
    

  
    SELECT COUNT(DISTINCT d.descripcion)
      INTO l_cant_diagnosticos
      FROM diagnosticos d
      JOIN citas      c ON d.id_cita      = c.id_cita
      JOIN pacientes  p ON c.id_paciente  = p.id_paciente
     WHERE p.apellido = p_apellido
       AND p.dni      = p_dni;

    RETURN l_cant_diagnosticos;
END obtener_cant_diagnosticos;
/

-- Bloque de prueba
DECLARE
    l_resultado NUMBER;
BEGIN
    l_resultado := obtener_cant_diagnosticos('Perez', '12345678');
    DBMS_OUTPUT.PUT_LINE('Diagnósticos distintos: ' || l_resultado);
    IF l_resultado = -1  THEN DBMS_OUTPUT.PUT_LINE('Paciente no encontrado');
ELSIF l_resultado = -10 THEN DBMS_OUTPUT.PUT_LINE('Paciente duplicado');
ELSE DBMS_OUTPUT.PUT_LINE('Diagnósticos: ' || l_resultado);
END IF;

END;
/

*/
--2)Realizar un disparador que registre el usuario y la fecha de cualquier actividad de cambio que se realice sobre 
--- la tabla de pacientes (actualizaciones, eliminaciones o inserciones de registros).
--- Registrar esto en la tabla de LOGS_PACIENTES (tiene tres campos: ID, USUARIO, FECHA, MOTIVO).

/* 

CREATE TABLE logs_pacientes(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR2(100),
    fecha DATE,
    motivo VARCHAR2(255)
);

CREATE OR REPLACE TRIGGER trg_logs_consultas
    AFTER INSERT OR UPDATE OR DELETE ON pacientes
    FOR EACH ROW 
DECLARE
   
    v_motivo VARCHAR2(255);
BEGIN 
    IF INSERTING THEN 
        v_motivo := 'Insercion de Paciente ID: ' || :NEW.id_paciente;
    ELSIF UPDATING THEN 
        v_motivo := 'Actualizacion de Paciente ID: ' || :OLD.id_paciente;
    ELSIF DELETING THEN 
        v_motivo := 'Eliminacion de Paciente ID: ' || :OLD.id_paciente;
    END IF;
    INSERT INTO logs_pacientes(usuario, fecha, motivo) VALUES (USER, SYSDATE, v_motivo);
END;
/


BEGIN 

    INSERT INTO pacientes (nombre, apellido, dni, fecha_nacimiento, direccion, telefono, email,id_obra_social) 
                    VALUES ('sergio', 'tschernitschek', '32384844', TO_DATE('1986-07-01','YYYY-MM-DD'), 'rivadavia', '113', 'sergiots1786@gmail.com',1);

    UPDATE pacientes SET telefono = '1161930819' WHERE dni = '32384844';

    DELETE FROM pacientes WHERE dni = '32384844';

    FOR logs IN (SELECT * FROM LOGS_PACIENTES) LOOP 
        DBMS_OUTPUT.PUT_LINE(' Usuario: '|| logs.USUARIO || 'LOG ID: '||logs.ID  || 'Motivo: ' || logs.MOTIVO  );
    END LOOP;
END;
/
*/
--3)Crear una función que indique cuántos días de internación lleva un paciente determinado.
--- Si el paciente ha sido dado de alta indicarlo con -1 y con -10 si el paciente nunca ha sido internado en el nosocomio. 

CREATE OR REPLACE FUNCTION dias_internacion(
    p_id_paciente IN internaciones.id_paciente%TYPE
) RETURN NUMBER
IS
    v_fecha_ingreso internaciones.fecha_ingreso%TYPE;
    v_fecha_egreso  internaciones.fecha_egreso%TYPE;
BEGIN
    SELECT fecha_ingreso, fecha_egreso
    INTO v_fecha_ingreso, v_fecha_egreso
    FROM internaciones
    WHERE id_paciente = p_id_paciente
      AND fecha_egreso IS NULL;

    RETURN TRUNC(current_date - v_fecha_ingreso);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DECLARE
            v_cont NUMBER;
        BEGIN
            SELECT COUNT(*)
            INTO v_cont
            FROM internaciones
            WHERE id_paciente = p_id_paciente;

            IF v_cont = 0 THEN
                RETURN -10;
            else
                return -1;    
            
            END IF;
        END;
END;
/
 
 --BLOQUE PRUEBA
DECLARE
 v_id_paciente internaciones.id_paciente%TYPE:= &Ingrese_ID_de_paciente;
 v_res number;
begin
 if v_res > 0 then
  v_res := dias_internacion(v_id_paciente);
  DBMS_OUTPUT.PUT_LINE('Dias de internacion: '||v_res);
  elsif v_res = -10 then
        DBMS_OUTPUT.PUT_LINE('Paciente nunca ingresado a internacion');
   else
        DBMS_OUTPUT.PUT_LINE('Paciente dado de alta');     
    
   
 end if;
end;




--4)Mediante un procedimiento almacenado hacer el listado de todos los pacientes que se atienden en el 
--nosocomio por Obra Social. El listado debe tener un encabezado por Obra Social con los datos más relevantes de ésta:
-- Nombre y Dirección, mientras que de los pacientes se pide Apellido, Nombre y dirección de correo electrónico
--Texto de la respuesta Pregunta 4

/*  
CREATE OR REPLACE PROCEDURE listado_por_obra_social AS

    
    CURSOR c_obras IS
        SELECT id_obra_social, nombre, direccion
        FROM obras_sociales;

   
    CURSOR c_pacientes(p_id obras_sociales.id_obra_social%TYPE) IS
        SELECT apellido, nombre, email
        FROM pacientes
        WHERE id_obra_social = p_id;

BEGIN
    FOR os IN c_obras LOOP

        
        DBMS_OUTPUT.PUT_LINE('-----'||'OBRA SOCIAL'||os.nombre || '  Direccion: ' || os.direccion ||'----');

        
        FOR p IN c_pacientes(os.id_obra_social) LOOP
            DBMS_OUTPUT.PUT_LINE('  ' || p.apellido || ', ' || p.nombre || ' - ' || p.email);
        END LOOP;

    END LOOP;
END listado_por_obra_social;


-- bloque de prueba
BEGIN
    listado_por_obra_social;
END;
*/