-- ============================================================
-- CORRECCIÓN Y ANÁLISIS - PARCIAL 1
-- Base de Datos II - Sanatorio "Urgencias Locas"
-- Alumno: Tschernitschek - Legajo: 38377
-- ============================================================


-- ============================================================
-- EJERCICIO 1
-- Función: obtener_cant_diagnosticos
-- Retorna la cantidad de diagnósticos DISTINTOS de un paciente.
-- Si hay dos pacientes con mismo apellido y DNI → retorna -10.
-- Si el paciente no existe → retorna 0.
-- ============================================================

CREATE OR REPLACE FUNCTION obtener_cant_diagnosticos(
    p_apellido IN pacientes.apellido%TYPE,  -- Parámetro de entrada: apellido del paciente
    p_dni      IN pacientes.dni%TYPE        -- Parámetro de entrada: DNI del paciente
) RETURN NUMBER IS
    l_cant_pacientes    NUMBER;  -- Variable para detectar duplicados o ausencia
    l_cant_diagnosticos NUMBER;  -- Variable para almacenar el resultado final
BEGIN
    -- Contamos cuántos pacientes coinciden con ese apellido y DNI.
    -- COUNT(*) cuenta todas las filas que cumplen WHERE, nunca devuelve NULL.
    SELECT COUNT(*)
      INTO l_cant_pacientes        -- Guardamos el resultado en la variable local
      FROM pacientes
     WHERE apellido = p_apellido
       AND dni      = p_dni;

    -- Regla de negocio: más de 1 resultado significa pacientes duplicados
    IF l_cant_pacientes > 1 THEN
        RETURN -10;
    -- Sin resultados: el paciente no existe en el sistema
    ELSIF l_cant_pacientes = 0 THEN
        RETURN 0;
    END IF;

    -- Exactamente 1 paciente encontrado: contamos sus diagnósticos distintos.
    -- COUNT(DISTINCT d.descripcion) evita contar el mismo diagnóstico más de una vez.
    -- Se navega: diagnosticos → citas → pacientes mediante JOINs.
    SELECT COUNT(DISTINCT d.descripcion)
      INTO l_cant_diagnosticos
      FROM diagnosticos d
      JOIN citas     c ON d.id_cita     = c.id_cita      -- Une diagnóstico con su cita
      JOIN pacientes p ON c.id_paciente = p.id_paciente  -- Une cita con el paciente
     WHERE p.apellido = p_apellido
       AND p.dni      = p_dni;

    RETURN l_cant_diagnosticos;
END obtener_cant_diagnosticos;
/

-- ---- Bloque de prueba ----
DECLARE
    l_resultado NUMBER;
BEGIN
    -- Invocamos la función con datos de prueba
    l_resultado := obtener_cant_diagnosticos('Perez', '12345678');
    DBMS_OUTPUT.PUT_LINE('Resultado raw: ' || l_resultado);

    -- Evaluamos el resultado DESPUÉS de ejecutar la función
    IF    l_resultado = -10 THEN DBMS_OUTPUT.PUT_LINE('Paciente duplicado');
    ELSIF l_resultado =   0 THEN DBMS_OUTPUT.PUT_LINE('Paciente no encontrado');
    ELSE                         DBMS_OUTPUT.PUT_LINE('Diagnósticos distintos: ' || l_resultado);
    END IF;
END;
/


-- ============================================================
-- EJERCICIO 2
-- Tabla de auditoría + Trigger: trg_logs_consultas
-- Auditoría de cambios sobre la tabla PACIENTES.
-- Se dispara DESPUÉS de INSERT, UPDATE o DELETE.
-- Registra en LOGS_PACIENTES: usuario DB, fecha y motivo.
-- ============================================================

-- Tabla de auditoría donde se registran todos los cambios.
-- GENERATED BY DEFAULT AS IDENTITY: autoincremento automático para el ID (Oracle 12c+).
CREATE TABLE logs_pacientes(
    id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR2(100),  -- Usuario de base de datos que ejecutó la acción (función USER)
    fecha   DATE,           -- Fecha y hora del evento (función SYSDATE)
    motivo  VARCHAR2(255)   -- Descripción del evento: inserción, actualización o eliminación
);

-- AFTER: el trigger se ejecuta DESPUÉS de que la operación DML impacta la tabla.
-- FOR EACH ROW: granularidad por fila (se ejecuta una vez por cada fila afectada).
-- :NEW → valores nuevos disponibles en INSERT y UPDATE.
-- :OLD → valores anteriores disponibles en UPDATE y DELETE.
CREATE OR REPLACE TRIGGER trg_logs_consultas
    AFTER INSERT OR UPDATE OR DELETE ON pacientes  -- Se activa tras cualquier cambio DML
    FOR EACH ROW                                   -- Una ejecución por fila modificada
DECLARE
    v_motivo VARCHAR2(255);  -- Variable local para construir el mensaje del log
BEGIN
    -- INSERTING, UPDATING, DELETING: predicados booleanos exclusivos de triggers.
    -- Retornan TRUE según el tipo de operación DML que disparó el trigger.
    IF INSERTING THEN
        -- :NEW.id_paciente: ID de la fila recién insertada
        v_motivo := 'Insercion de Paciente ID: ' || :NEW.id_paciente;
    ELSIF UPDATING THEN
        -- :OLD.id_paciente: ID de la fila antes de ser modificada
        v_motivo := 'Actualizacion de Paciente ID: ' || :OLD.id_paciente;
    ELSIF DELETING THEN
        -- :OLD.id_paciente: ID de la fila que está siendo eliminada
        v_motivo := 'Eliminacion de Paciente ID: ' || :OLD.id_paciente;
    END IF;

    -- USER    → nombre del usuario conectado a la sesión de base de datos
    -- SYSDATE → fecha y hora actual del servidor Oracle
    INSERT INTO logs_pacientes(usuario, fecha, motivo)
    VALUES (USER, SYSDATE, v_motivo);
END;
/

-- ---- Bloque de prueba ----
-- SAVEPOINT para poder deshacer los cambios de prueba y dejar la tabla limpia
BEGIN
    SAVEPOINT antes_prueba;

    -- INSERT: dispara la rama INSERTING del trigger
    INSERT INTO pacientes (nombre, apellido, dni, fecha_nacimiento, direccion, telefono, email, id_obra_social)
    VALUES ('sergio', 'tschernitschek', '32384844', TO_DATE('1986-07-01','YYYY-MM-DD'), 'rivadavia', '113', 'sergiots1786@gmail.com', 1);

    -- UPDATE: dispara la rama UPDATING del trigger
    UPDATE pacientes SET telefono = '1161930819' WHERE dni = '32384844';

    -- DELETE: dispara la rama DELETING del trigger
    DELETE FROM pacientes WHERE dni = '32384844';

    -- Cursor implícito en FOR-LOOP: itera los 3 registros generados en LOGS_PACIENTES
    FOR logs IN (SELECT * FROM LOGS_PACIENTES) LOOP
        DBMS_OUTPUT.PUT_LINE('Usuario: ' || logs.USUARIO || ' | LOG ID: ' || logs.ID || ' | Motivo: ' || logs.MOTIVO);
    END LOOP;

    -- Deshacemos los cambios de prueba para no contaminar la tabla
    ROLLBACK TO antes_prueba;
END;
/


-- ============================================================
-- EJERCICIO 3
-- Función: dias_internacion
-- Retorna los días que lleva internado un paciente activo.
-- Retorna -1  si el paciente ya fue dado de alta (tiene fecha_egreso).
-- Retorna -10 si el paciente nunca fue internado.
-- ============================================================

CREATE OR REPLACE FUNCTION dias_internacion(
    p_id_paciente IN internaciones.id_paciente%TYPE  -- ID del paciente a consultar
) RETURN NUMBER
IS
    -- %TYPE ancla el tipo de la variable al tipo real de la columna en la tabla.
    -- Ventaja: si la columna cambia de tipo, la función se adapta automáticamente.
    v_fecha_ingreso internaciones.fecha_ingreso%TYPE;
    v_fecha_egreso  internaciones.fecha_egreso%TYPE;
BEGIN
    -- Buscamos una internación ACTIVA: fecha_egreso IS NULL significa sin alta médica.
    -- Si no hay fila que cumpla → Oracle lanza NO_DATA_FOUND automáticamente.
    SELECT fecha_ingreso, fecha_egreso
      INTO v_fecha_ingreso, v_fecha_egreso
      FROM internaciones
     WHERE id_paciente = p_id_paciente
       AND fecha_egreso IS NULL;  -- Condición clave: solo internaciones activas

    -- TRUNC() elimina decimales del resultado de la resta de fechas,
    -- devolviendo días enteros sin fracción horaria.
    -- CURRENT_DATE: fecha actual según la zona horaria de la sesión.
    RETURN TRUNC(CURRENT_DATE - v_fecha_ingreso);

EXCEPTION
    -- NO_DATA_FOUND: el SELECT INTO no encontró fila con fecha_egreso IS NULL.
    -- Puede ser: dado de alta (tiene fecha_egreso) o nunca internado (sin registros).
    WHEN NO_DATA_FOUND THEN
        DECLARE
            v_cont NUMBER;  -- Contador para distinguir los dos casos posibles
        BEGIN
            -- Contamos TODAS las internaciones del paciente (con o sin fecha_egreso)
            SELECT COUNT(*)
              INTO v_cont
              FROM internaciones
             WHERE id_paciente = p_id_paciente;

            -- Sin registros en absoluto: el paciente nunca fue internado
            IF v_cont = 0 THEN
                RETURN -10;
            ELSE
                -- Hay registros pero todos tienen fecha_egreso → fue dado de alta
                RETURN -1;
            END IF;
        END;
END;
/

-- ---- Bloque de prueba (CORREGIDO) ----
-- BUG ORIGINAL: el IF evaluaba v_res ANTES de llamar a la función (v_res era NULL).
-- NULL > 0 siempre es FALSE en Oracle → la función nunca se ejecutaba.
-- CORRECCIÓN: primero ejecutar la función, después evaluar el resultado.
DECLARE
    v_id_paciente internaciones.id_paciente%TYPE := &Ingrese_ID_de_paciente;
    v_res         NUMBER;
BEGIN
    -- PASO 1: ejecutar la función y guardar el resultado
    v_res := dias_internacion(v_id_paciente);

    -- PASO 2: evaluar el resultado (ahora v_res tiene un valor, no es NULL)
    IF    v_res = -10 THEN DBMS_OUTPUT.PUT_LINE('Paciente nunca ingresado a internacion');
    ELSIF v_res = -1  THEN DBMS_OUTPUT.PUT_LINE('Paciente dado de alta');
    ELSE                   DBMS_OUTPUT.PUT_LINE('Dias de internacion activa: ' || v_res);
    END IF;
END;
/


-- ============================================================
-- EJERCICIO 4
-- Procedimiento: listado_por_obra_social
-- Lista todos los pacientes agrupados por obra social.
-- Encabezado por obra social: nombre y dirección.
-- Detalle por paciente: apellido, nombre y email.
-- ============================================================

CREATE OR REPLACE PROCEDURE listado_por_obra_social AS

    -- Cursor explícito c_obras: recorre todas las obras sociales.
    -- Un cursor explícito da control manual sobre la consulta.
    CURSOR c_obras IS
        SELECT id_obra_social, nombre, direccion
        FROM obras_sociales;

    -- Cursor parametrizado c_pacientes: recibe el ID de obra social como parámetro.
    -- Permite reutilizar el mismo cursor con distintos valores en cada iteración.
    CURSOR c_pacientes(p_id obras_sociales.id_obra_social%TYPE) IS
        SELECT apellido, nombre, email
        FROM pacientes
        WHERE id_obra_social = p_id;  -- Filtra pacientes de la obra social actual

BEGIN
    -- FOR...LOOP sobre cursor: Oracle abre, avanza y cierra el cursor automáticamente.
    -- La variable "os" es un registro implícito con los campos de la fila actual.
    FOR os IN c_obras LOOP

        -- Imprimimos encabezado por cada obra social
        DBMS_OUTPUT.PUT_LINE('=== OBRA SOCIAL: ' || os.nombre || ' | Dirección: ' || os.direccion || ' ===');

        -- Loop anidado: pasamos el ID de la obra social actual al cursor parametrizado.
        -- Si la obra social no tiene pacientes, este loop simplemente no ejecuta.
        FOR p IN c_pacientes(os.id_obra_social) LOOP
            DBMS_OUTPUT.PUT_LINE('  ' || p.apellido || ', ' || p.nombre || ' - ' || p.email);
        END LOOP;

    END LOOP;
END listado_por_obra_social;
/

-- ---- Bloque de prueba ----
BEGIN
    listado_por_obra_social;  -- Invocamos el procedimiento sin parámetros
END;
/


-- ============================================================
-- ============================================================
--       GLOSARIO DE FUNCIONES BUILT-IN UTILIZADAS
-- ============================================================
-- ============================================================

/*
┌──────────────────────────┬────────────────────────────────────────────────────────────────────────┐
│ Función / Keyword         │ Sintaxis y Funcionamiento                                              │
├──────────────────────────┼────────────────────────────────────────────────────────────────────────┤
│ COUNT(*)                  │ COUNT(*)                                                               │
│                           │ Cuenta TODAS las filas que cumplen WHERE, incluyendo NULLs.            │
│                           │ Nunca retorna NULL: el mínimo es 0.                                    │
│                           │ Ej: SELECT COUNT(*) FROM pacientes WHERE dni = '123'                   │
├──────────────────────────┼────────────────────────────────────────────────────────────────────────┤
│ COUNT(DISTINCT expr)      │ COUNT(DISTINCT columna)                                                │
│                           │ Cuenta valores únicos, ignorando NULLs y duplicados.                  │
│                           │ Ej: COUNT(DISTINCT d.descripcion) → no repite el mismo diagnóstico    │
├──────────────────────────┼────────────────────────────────────────────────────────────────────────┤
│ TRUNC(n)                  │ TRUNC(valor [, posicion])                                              │
│ TRUNC(fecha)              │ Números: elimina decimales sin redondear. TRUNC(5.9) → 5               │
│                           │ Fechas:  elimina la parte horaria. TRUNC(SYSDATE) → hoy a medianoche  │
│                           │ Ej: TRUNC(CURRENT_DATE - fecha_ingreso) → días enteros                │
├──────────────────────────┼────────────────────────────────────────────────────────────────────────┤
│ CURRENT_DATE              │ CURRENT_DATE                                                           │
│                           │ Fecha actual según zona horaria de la SESIÓN (no del servidor).       │
│                           │ Sin paréntesis. Alternativa sensible a timezone de SYSDATE.           │
├──────────────────────────┼────────────────────────────────────────────────────────────────────────┤
│ SYSDATE                   │ SYSDATE                                                                │
│                           │ Fecha y hora actual del SERVIDOR de base de datos.                    │
│                           │ Sin paréntesis. Estándar Oracle para registros de auditoría.          │
│                           │ Ej: INSERT INTO logs(fecha) VALUES(SYSDATE)                           │
├──────────────────────────┼────────────────────────────────────────────────────────────────────────┤
│ USER                      │ USER                                                                   │
│                           │ Retorna el nombre del usuario conectado en la sesión DB.               │
│                           │ Sin paréntesis. Ej: INSERT INTO logs(usuario) VALUES(USER)            │
├──────────────────────────┼────────────────────────────────────────────────────────────────────────┤
│ TO_DATE                   │ TO_DATE(cadena, formato)                                               │
│                           │ Convierte un VARCHAR2 en DATE usando una máscara de formato.          │
│                           │ Ej: TO_DATE('1986-07-01', 'YYYY-MM-DD') → valor DATE 01/07/1986       │
├──────────────────────────┼────────────────────────────────────────────────────────────────────────┤
│ DBMS_OUTPUT.PUT_LINE      │ DBMS_OUTPUT.PUT_LINE(texto VARCHAR2)                                   │
│                           │ Imprime texto en consola. Requiere SET SERVEROUTPUT ON.               │
│                           │ Ej: DBMS_OUTPUT.PUT_LINE('Resultado: ' || v_numero)                   │
├──────────────────────────┼────────────────────────────────────────────────────────────────────────┤
│ NO_DATA_FOUND             │ WHEN NO_DATA_FOUND THEN ...                                            │
│                           │ Excepción predefinida que Oracle lanza cuando un SELECT INTO          │
│                           │ no encuentra ninguna fila. Se captura en el bloque EXCEPTION.         │
├──────────────────────────┼────────────────────────────────────────────────────────────────────────┤
│ TOO_MANY_ROWS             │ WHEN TOO_MANY_ROWS THEN ...                                            │
│                           │ Excepción predefinida que Oracle lanza cuando un SELECT INTO          │
│                           │ devuelve MÁS de una fila. Complemento de NO_DATA_FOUND.              │
├──────────────────────────┼────────────────────────────────────────────────────────────────────────┤
│ GENERATED BY DEFAULT      │ columna NUMBER GENERATED BY DEFAULT AS IDENTITY                        │
│ AS IDENTITY               │ Autoincremento automático para la columna (Oracle 12c+).              │
│                           │ "BY DEFAULT" permite también insertar valores manuales.               │
│                           │ Alternativa moderna a CREATE SEQUENCE.                                │
├──────────────────────────┼────────────────────────────────────────────────────────────────────────┤
│ INSERTING / UPDATING      │ IF INSERTING / ELSIF UPDATING / ELSIF DELETING                        │
│ / DELETING                │ Predicados booleanos disponibles SOLO dentro de triggers.             │
│                           │ Retornan TRUE según el DML que disparó el trigger.                   │
│                           │ Permiten manejar INSERT, UPDATE y DELETE en un solo trigger.          │
├──────────────────────────┼────────────────────────────────────────────────────────────────────────┤
│ :NEW / :OLD               │ :NEW.columna  /  :OLD.columna                                          │
│                           │ Pseudoregistros disponibles en triggers FOR EACH ROW.                 │
│                           │ :NEW → valor nuevo (INSERT y UPDATE). No disponible en DELETE.        │
│                           │ :OLD → valor anterior (UPDATE y DELETE). No disponible en INSERT.     │
├──────────────────────────┼────────────────────────────────────────────────────────────────────────┤
│ SAVEPOINT / ROLLBACK TO   │ SAVEPOINT nombre;  /  ROLLBACK TO nombre;                             │
│                           │ SAVEPOINT crea un punto de restauración dentro de una transacción.   │
│                           │ ROLLBACK TO deshace cambios hasta ese punto sin cancelar todo.        │
│                           │ Útil para pruebas que no deben persistir en la base de datos.        │
└──────────────────────────┴────────────────────────────────────────────────────────────────────────┘
*/


-- ============================================================
-- ============================================================
--          SUGERENCIAS DE MEJORA PARA LOS SCRIPTS
-- ============================================================
-- ============================================================

/*
=== SUGERENCIA 1 — BUG CRÍTICO en el bloque de prueba del Ejercicio 3 ===

CÓDIGO ORIGINAL (incorrecto):
    v_res NUMBER;             -- v_res = NULL en este punto
BEGIN
    IF v_res > 0 THEN         -- NULL > 0 → siempre FALSE en Oracle, nunca entra
        v_res := dias_internacion(v_id_paciente);  -- NUNCA SE EJECUTA

PROBLEMA: En Oracle, cualquier comparación con NULL devuelve NULL (que es falso en un IF).
v_res es NULL cuando se evalúa el IF, por lo que la función nunca se invoca.
El bloque termina sin mostrar nada ni lanzar error → falla silenciosa.

CÓDIGO CORREGIDO (ya aplicado):
    v_res := dias_internacion(v_id_paciente);  -- Primero ejecutamos la función
    IF    v_res = -10 THEN ...                 -- Después evaluamos el resultado
    ELSIF v_res = -1  THEN ...
    ELSE  ...


=== SUGERENCIA 2 — Agregar SAVEPOINT en el bloque de prueba del Ejercicio 2 ===

El bloque de prueba hace INSERT + UPDATE + DELETE reales sobre la tabla pacientes.
Si algo falla a mitad del bloque, los cambios parciales quedan confirmados.
Solución: envolver en SAVEPOINT y hacer ROLLBACK al final de la prueba.

    BEGIN
        SAVEPOINT antes_prueba;
        INSERT INTO pacientes ...;
        UPDATE pacientes ...;
        DELETE FROM pacientes ...;
        FOR logs IN (SELECT * FROM LOGS_PACIENTES) LOOP ... END LOOP;
        ROLLBACK TO antes_prueba;  -- Deja la tabla limpia después de la prueba
    END;

Ya aplicado en este archivo.


=== SUGERENCIA 3 — Usar RAISE_APPLICATION_ERROR en lugar de códigos mágicos ===

Retornar -1 y -10 como códigos de error funciona, pero es frágil:
quien llama a la función debe saber de memoria qué significa cada número.
Una alternativa más robusta y descriptiva:

    RAISE_APPLICATION_ERROR(-20001, 'Paciente no encontrado');
    RAISE_APPLICATION_ERROR(-20002, 'Paciente duplicado - apellido y DNI ambiguos');

Los códigos -20000 a -20999 están reservados para errores de usuario en Oracle.
El error se propaga con un mensaje claro en lugar de un número arbitrario.


=== SUGERENCIA 4 — Manejar TOO_MANY_ROWS explícitamente ===

En el Ejercicio 1, el enfoque con COUNT(*) es correcto y evita TOO_MANY_ROWS.
Pero conviene conocer la excepción para defenderla:

    Si hubieras usado SELECT ... INTO directamente sin COUNT,
    Oracle lanzaría TOO_MANY_ROWS cuando dos pacientes coincidan.
    Tu elección de usar COUNT primero es la más segura y correcta.

Ejemplo de cómo se vería con excepción explícita (alternativa menos recomendada):
    EXCEPTION
        WHEN TOO_MANY_ROWS THEN RETURN -10;
        WHEN NO_DATA_FOUND THEN RETURN 0;


=== SUGERENCIA 5 — Consistencia entre CURRENT_DATE y SYSDATE ===

En el Ejercicio 2 usás SYSDATE y en el Ejercicio 3 usás CURRENT_DATE.
Ambas retornan la fecha actual, pero:
  - SYSDATE    → zona horaria del SERVIDOR (más común en sistemas Oracle)
  - CURRENT_DATE → zona horaria de la SESIÓN del usuario

En un sistema donde servidor y clientes están en distintas zonas horarias,
mezclar ambas puede generar diferencias horarias difíciles de depurar.
Recomendación: elegí una sola y usala en todo el proyecto.
Estándar histórico de Oracle: SYSDATE.


=== SUGERENCIA 6 — Formato de DBMS_OUTPUT en el Ejercicio 2 ===

En el loop de logs del bloque de prueba original faltaba separación entre campos:
    ' Usuario: '|| logs.USUARIO || 'LOG ID: '  ← sin separador visible entre campos

Versión mejorada aplicada en este archivo:
    'Usuario: ' || logs.USUARIO || ' | LOG ID: ' || logs.ID || ' | Motivo: ' || logs.MOTIVO

Pequeño detalle de presentación, pero en una defensa se nota el cuidado.
*/
