/*  SE DISPONE DE LOS SIGUIENTES ARCHIVOS :

ARTICULOS.TXT
CUENTOS.TXT
OPINIONES.TXT
PARRAFOS.TXT
RELATOS.TXT
RESUMEN.TXT
TEXTOS.TXT
VERSIONES.TXT

LOS CONTENIDOS DE LOS ARCHIVOS TIENEN LIGERAS DIFERENMCIAS EXCEPTO DOS DE ELLOS QUE SON IGUALES.
CONSTRUIR EL PROGRAMA MUESTRE CUALES SON ESTOS ARCHIVOS.

*/

	
	

